//
//  DataModelMK61.swift
//  RPN35
//
//  Created by Enrique Haro on 3/1/25.
//

import Foundation

extension DataModel {
    var mk61Keys: [Key] {
        [
            // Row 0
            Key(type: .mkYellow, ops: [.fShift],
                "F", "", 20, 0, 0),
            Key(type: .gray, ops: [.wr],
                Cyrilic.wr, "", 13, 0, 0,
                "x<0", "", 15),
            Key(type: .gray, ops: [.rw],
                Cyrilic.wr, "", 13, 0, 0,
                "x>0", "", 15),
            Key(type: .gray, ops: [.none],
                "B/O", "", 15, 0, 0,
                "x\(Sym.greaterEqual)0", "", 15),
            Key(type: .gray, ops: [.none],
                "C/", Cyrilic.p, 15, 15, 0,
                "x\(Sym.notEqual)0", "", 15),
            // Row 1
            Key(type: .mkBlue, ops: [.none],
                "K", "", 20, 0, 0),
            Key(type: .gray, ops: [.nx],
                "\(Cyrilic.p)\(Sym.rightArrow)\(Cyrilic.x)", "", 14, 0, 0,
                "L0", "", 15),
            Key(type: .gray, ops: [.xn],
                "\(Cyrilic.x)\(Sym.rightArrow)\(Cyrilic.p)", "", 14, 0, 0,
                "L1", "", 15),
            Key(type: .gray, ops: [.none],
                Cyrilic.dn, "", 15, 0, 0,
                "L2", "", 15),
            Key(type: .gray, ops: [.none],
                Cyrilic.nn, "", 15, 0, 0,
                "L3", "", 15),
            // Row 2
            Key(type: .mkWhite, ops: [.digit("7"), .sin],
                "7", "", 22, 0, 0,
                "sin", "", 15, 0, 0,
                "[x]", "", 15),
            Key(type: .mkWhite, ops: [.digit("8"), .cos],
                "8", "", 22, 0, 0,
                "cos", "", 15, 0, 0,
                "{x}", "", 15),
            Key(type: .mkWhite, ops: [.digit("9"), .tan],
                "9", "", 22, 0, 0,
                "tg", "", 15, 0, 0,
                "max", "", 15),
            Key(type: .mkWhite, ops: [.substract, .sqrt],
                "", Sym.substract, 0, 32, 0,
                Sym.sqrt, "", 15),
            Key(type: .mkWhite, ops: [.divide, .inverse],
                "", Sym.divide, 0, 32, 2, "1/",
                Sym.x, 15, 15, 0),
            // Row 3
            Key(type: .mkWhite, ops: [.digit("4"), .asin, .abs],
                "4", "", 22, 0, 0,
                "sin", "-1", 15, 10, 5,
                "|x|", "", 15),
            Key(type: .mkWhite, ops: [.digit("5"), .acos],
                "5", "", 22, 0, 0,
                "cos", "-1", 15, 10, 5,
                Cyrilic.eh, "", 13),
            Key(type: .mkWhite, ops: [.digit("6"), .atan],
                "6", "", 22, 0, 0,
                "tg", "-1", 15, 10, 5),
            Key(type: .mkWhite, ops: [.add, .pi], "",
                Sym.add, 0, 32, 3,
                Sym.pi, "", 18, 0, 0),
            Key(type: .mkWhite, ops: [.multiply, .powTwo],
                "", Sym.multiply, 0, 32, 4,
                Sym.x, "2", 15, 10, 6),
            // Row 4
            Key(type: .mkWhite, ops: [.digit("1"), .ex],
                "1", "", 22, 0, 0,
                Sym.e, Sym.x, 18, 12, 8),
            Key(type: .mkWhite, ops: [.digit("2"), .log],
                "2", "", 22, 0, 0,
                "lg", "", 15),
            Key(type: .mkWhite, ops: [.digit("3"), .ln],
                "3", "", 22, 0, 0,
                "ln", "", 15),
            Key(type: .mkWhite, ops: [.exchangeXY, .powerXY],
                Sym.leftRightArrow, "", 18, 0, 0,
                Sym.x, Sym.y, 14, 12, 8),
            Key(type: .mkWhite, ops: [.enter],
                Cyrilic.b, Sym.up35, 20, 20, 0,
                Cyrilic.b, Cyrilic.x, 15, 12, -4,
                "C4", "", 15),
            // Row 5
            Key(type: .mkWhite, ops: [.digit("0"), .tenX],
                "0", "", 22, 0, 0,
                "10", Sym.x, 15, 13, 12,
                Cyrilic.hon, "", 13),
            Key(type: .mkWhite, ops: [.digit(".")],
                Sym.dot, "", 20, 0, 0,
                Sym.lineCircle, "", 20, 0, 0,
                "", Sym.upChevron, 0, 18, -8),
            Key(type: .mkWhite, ops: [.none],
                "/ - /", "", 18, 0, 0,
                "ABT", "", 15, 0, 0,
                "", Sym.downChevron, 0, 20, 10),
            Key(type: .mkWhite, ops: [.none],
                Cyrilic.bn, "", 20, 0, 0,
                Cyrilic.nrp, "", 15, 0, 0,
                Sym.plusCircle),
            Key(type: .mkRed, ops: [.clrX, .clr],
                Cyrilic.cx, "", 20, 0, 0,
                "CF", "", 15, 0, 0,
                Cyrilic.nhb, "", 15),

// NOT USED
            Key(type: .mkWhite, ops: [.sto(0, op: .none), .toDMS], "STO", "", 14, 0, 0,
                                       Sym.right, "D.MS", 8, 12, 0),
            Key(type: .mkWhite, ops: [.rcl(0, op: .none), .fromDMS], "RCL", "", 14, 0, 0,
                                       "D.MS", Sym.right, 12, 8, 0),
            Key(type: .mkWhite, ops: [.percentage, .delta], "%", "", 16, 0, 0,
                                                         "", "\(Sym.delta)%", 0, 14, 2),
            Key(type: .mkWhite, ops: [.exchangeXY, .factorial], "", Sym.exchange, 0, 14, 4,
                                                                  "", "n!", 0, 16, 2),
            Key(type: .mkWhite, ops: [.rotateDown, .stdDev], "", "R\(Sym.down35)", 0, 14, 2,
                                                               "", "\(Sym.x)\(Sym.macron), s", 0, 16, 2),
            //            Key(type: .gray, ops: [.sin, .asin], "SIN", "", 14, 0, 0,
            //                                                "SIN", "-1", 13, 10, 6),
            //            Key(type: .gray, ops: [.cos, .acos], "COS", "", 14, 0, 0,
            //                                                "COS", "-1", 13, 10, 6),
            //            Key(type: .gray, ops: [.tan, .atan], "TAN", "", 14, 0, 0,
            //                                                "TAN", "-1", 13, 10, 6),
        Key(type: .gray, ops: [.toP, .toR], Sym.right, "P", 10, 14, 0,
                                                 Sym.right, "R", 10, 14, 2)
        ]
    }
}
